// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto_CPS.Data;

#nullable disable

namespace Proyecto_CPS.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Proyecto_CPS.Models.Boleta", b =>
                {
                    b.Property<int>("IdBoleta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdBoleta"));

                    b.Property<DateTime>("FechaEmicion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumBoleta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdBoleta");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("Boletas");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.CategoriaMenu", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NombreDeCategoria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("CategoriaMenus");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Aperitivos y entradas",
                            NombreDeCategoria = "Entradas"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Platos principales",
                            NombreDeCategoria = "Platos Fuertes"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Descripcion = "Dulces y postres",
                            NombreDeCategoria = "Postres"
                        },
                        new
                        {
                            IdCategoria = 4,
                            Descripcion = "Refrescos y bebidas",
                            NombreDeCategoria = "Bebidas"
                        });
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("ApellidoM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PrimNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Comentario", b =>
                {
                    b.Property<int>("IdComentario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdComentario"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaComentario")
                        .HasColumnType("datetime2");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.HasKey("IdComentario");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MenuId");

                    b.ToTable("Comentarios");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.DetalleMenuPedido", b =>
                {
                    b.Property<int>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePedido"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("IdDetallePedido");

                    b.HasIndex("MenuId");

                    b.HasIndex("PedidoId");

                    b.ToTable("DetalleMenuPedidos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.DetalleMetodoPago", b =>
                {
                    b.Property<int>("IdDetallePago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetallePago"));

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoPago")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PagoId")
                        .HasColumnType("int");

                    b.HasKey("IdDetallePago");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("PagoId");

                    b.ToTable("DetalleMetodosPago");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("ApellidoM")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoP")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaContrato")
                        .HasColumnType("datetime2");

                    b.Property<string>("PrimNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("SegNombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("RolId");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.EmpleadoTurno", b =>
                {
                    b.Property<int>("IdEmpleadoTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleadoTurno"));

                    b.Property<int>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaTurno")
                        .HasColumnType("datetime2");

                    b.Property<int>("TurnoId")
                        .HasColumnType("int");

                    b.HasKey("IdEmpleadoTurno");

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("TurnoId");

                    b.ToTable("EmpleadoTurnos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Menu", b =>
                {
                    b.Property<int>("IdMenu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMenu"));

                    b.Property<int>("CategoriaMenuId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImagenUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdMenu");

                    b.HasIndex("CategoriaMenuId");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            IdMenu = 1,
                            CategoriaMenuId = 1,
                            Descripcion = "Papas amarillas con salsa de ají amarillo, queso fresco y huevo",
                            ImagenUrl = "https://i.postimg.cc/R0qnrWjS/papa-huancaina.jpg",
                            Nombre = "Papa a la Huancaína",
                            Precio = 18.00m
                        },
                        new
                        {
                            IdMenu = 2,
                            CategoriaMenuId = 1,
                            Descripcion = "Papas con salsa de huacatay, ají mirasol y maní tostado",
                            ImagenUrl = "https://i.postimg.cc/T33Kmy2X/ocopa.jpg",
                            Nombre = "Ocopa Jesusana",
                            Precio = 20.00m
                        },
                        new
                        {
                            IdMenu = 3,
                            CategoriaMenuId = 2,
                            Descripcion = "Salteado de lomo fino con cebolla, tomate y papas fritas",
                            ImagenUrl = "https://i.postimg.cc/pLSLFq1Z/lomo-salt.jpg",
                            Nombre = "Lomo Saltado",
                            Precio = 35.00m
                        },
                        new
                        {
                            IdMenu = 4,
                            CategoriaMenuId = 2,
                            Descripcion = "Rocoto relleno de carne molida, queso y hierbas aromáticas",
                            ImagenUrl = "https://i.postimg.cc/g0Rm6dhZ/rocoto.webp",
                            Nombre = "Rocoto Relleno",
                            Precio = 28.00m
                        },
                        new
                        {
                            IdMenu = 5,
                            CategoriaMenuId = 2,
                            Descripcion = "Cuy frito bajo una piedra con papas y salsa criolla",
                            ImagenUrl = "https://i.postimg.cc/vTZJXd4D/cuy.jpg",
                            Nombre = "Cuy Chactado",
                            Precio = 45.00m
                        },
                        new
                        {
                            IdMenu = 6,
                            CategoriaMenuId = 2,
                            Descripcion = "Trucha fresca frita con yuca y ensalada andina",
                            ImagenUrl = "https://i.postimg.cc/1XXdwcdk/trucha.webp",
                            Nombre = "Trucha Frita",
                            Precio = 32.00m
                        },
                        new
                        {
                            IdMenu = 7,
                            CategoriaMenuId = 2,
                            Descripcion = "Caldo nutritivo con gallina criolla, fideos y hierbas",
                            ImagenUrl = "https://i.postimg.cc/zBB7cDk5/caldo-gallina.jpg",
                            Nombre = "Caldo de Gallina",
                            Precio = 25.00m
                        },
                        new
                        {
                            IdMenu = 8,
                            CategoriaMenuId = 3,
                            Descripcion = "Postre de maíz morado con frutas deshidratadas",
                            ImagenUrl = "https://i.postimg.cc/L4rdLGHz/mazamorra.webp",
                            Nombre = "Mazamorra Morada",
                            Precio = 12.00m
                        },
                        new
                        {
                            IdMenu = 9,
                            CategoriaMenuId = 3,
                            Descripcion = "Anillos fritos de camote y zapato con miel de chancaca",
                            ImagenUrl = "https://i.postimg.cc/MTNL0j8p/picarones.jpg",
                            Nombre = "Picarones",
                            Precio = 15.00m
                        },
                        new
                        {
                            IdMenu = 10,
                            CategoriaMenuId = 4,
                            Descripcion = "Refresco tradicional de maíz morado con especias",
                            ImagenUrl = "https://i.postimg.cc/nrfkcKJZ/chicha.webp",
                            Nombre = "Chicha Morada",
                            Precio = 8.00m
                        },
                        new
                        {
                            IdMenu = 11,
                            CategoriaMenuId = 4,
                            Descripcion = "Bebida caliente de hierbas andinas con linaza",
                            ImagenUrl = "https://i.postimg.cc/4N55shFT/emoliente.jpg",
                            Nombre = "Emoliente",
                            Precio = 6.00m
                        },
                        new
                        {
                            IdMenu = 12,
                            CategoriaMenuId = 4,
                            Descripcion = "Infusión de hojas de coca para el mal de altura",
                            ImagenUrl = "https://i.postimg.cc/MTV74cQ2/mate-coca.webp",
                            Nombre = "Mate de Coca",
                            Precio = 5.00m
                        });
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMesa"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<int>("NumMesa")
                        .HasColumnType("int");

                    b.HasKey("IdMesa");

                    b.ToTable("Mesas");

                    b.HasData(
                        new
                        {
                            IdMesa = 1,
                            Capacidad = 4,
                            NumMesa = 1
                        },
                        new
                        {
                            IdMesa = 2,
                            Capacidad = 4,
                            NumMesa = 2
                        },
                        new
                        {
                            IdMesa = 3,
                            Capacidad = 6,
                            NumMesa = 3
                        },
                        new
                        {
                            IdMesa = 4,
                            Capacidad = 6,
                            NumMesa = 4
                        },
                        new
                        {
                            IdMesa = 5,
                            Capacidad = 2,
                            NumMesa = 5
                        },
                        new
                        {
                            IdMesa = 6,
                            Capacidad = 8,
                            NumMesa = 6
                        },
                        new
                        {
                            IdMesa = 7,
                            Capacidad = 4,
                            NumMesa = 7
                        });
                });

            modelBuilder.Entity("Proyecto_CPS.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodoDePago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMetodoDePago"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdMetodoDePago");

                    b.ToTable("MetodosPago");

                    b.HasData(
                        new
                        {
                            IdMetodoDePago = 1,
                            Nombre = "Yape"
                        },
                        new
                        {
                            IdMetodoDePago = 2,
                            Nombre = "Plin"
                        });
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Orden", b =>
                {
                    b.Property<int>("IdOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrden"));

                    b.Property<string>("EstadoCocina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("IdOrden");

                    b.HasIndex("PedidoId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<int>("BoletaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPago");

                    b.HasIndex("BoletaId");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedido"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaPedido")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("IdPedido");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.PedidoMetodoPago", b =>
                {
                    b.Property<int>("IdPedidoMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPedidoMetodoPago"));

                    b.Property<DateTime>("FechaSeleccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoPagoId")
                        .HasColumnType("int");

                    b.Property<int>("PedidoId")
                        .HasColumnType("int");

                    b.HasKey("IdPedidoMetodoPago");

                    b.HasIndex("MetodoPagoId");

                    b.HasIndex("PedidoId")
                        .IsUnique();

                    b.ToTable("PedidoMetodoPagos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("ClienteId");

                    b.HasIndex("MesaId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NombreRol = "Mesero"
                        },
                        new
                        {
                            IdRol = 2,
                            NombreRol = "Cocinero"
                        },
                        new
                        {
                            IdRol = 3,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 4,
                            NombreRol = "Cliente"
                        });
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTurno"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.HasKey("IdTurno");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<int?>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("EmpleadoId")
                        .HasColumnType("int");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("ClienteId")
                        .IsUnique()
                        .HasFilter("[ClienteId] IS NOT NULL");

                    b.HasIndex("EmpleadoId")
                        .IsUnique()
                        .HasFilter("[EmpleadoId] IS NOT NULL");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Contrasena = "123456789",
                            Correo = "admin@puquio.com",
                            Estado = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreUsuario = "admin",
                            RolId = 3
                        },
                        new
                        {
                            IdUsuario = 2,
                            Contrasena = "123456789",
                            Correo = "mesero@puquio.com",
                            Estado = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreUsuario = "mesero",
                            RolId = 1
                        },
                        new
                        {
                            IdUsuario = 3,
                            Contrasena = "123456789",
                            Correo = "cocinero@puquio.com",
                            Estado = true,
                            FechaCreacion = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreUsuario = "cocinero",
                            RolId = 2
                        });
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Boleta", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.Pedido", "Pedidos")
                        .WithOne("Boletas")
                        .HasForeignKey("Proyecto_CPS.Models.Boleta", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Comentario", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.Cliente", "Clientes")
                        .WithMany("Comentarios")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_CPS.Models.Menu", "Menus")
                        .WithMany("Comentarios")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Menus");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.DetalleMenuPedido", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.Menu", "Menu")
                        .WithMany("DetalleMenuPedidos")
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_CPS.Models.Pedido", "Pedido")
                        .WithMany("DetalleMenuPedidos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Menu");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.DetalleMetodoPago", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.MetodoPago", "MetodoPagos")
                        .WithMany("DetalleMetodoPagos")
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_CPS.Models.Pago", "Pagos")
                        .WithMany("DetallesMetodoPagos")
                        .HasForeignKey("PagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPagos");

                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Empleado", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.Rol", "Rol")
                        .WithMany("Empleados")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.EmpleadoTurno", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.Empleado", "Empleados")
                        .WithMany("EmpleadoTurnos")
                        .HasForeignKey("EmpleadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_CPS.Models.Turno", "Turnos")
                        .WithMany("EmpleadoTurnos")
                        .HasForeignKey("TurnoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleados");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Menu", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.CategoriaMenu", "CategoriaMenus")
                        .WithMany("Menus")
                        .HasForeignKey("CategoriaMenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaMenus");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Orden", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.Pedido", "Pedido")
                        .WithMany("Ordenes")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Pago", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.Boleta", "Boleta")
                        .WithMany("Pagos")
                        .HasForeignKey("BoletaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Boleta");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Pedido", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.PedidoMetodoPago", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("MetodoPagoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_CPS.Models.Pedido", "Pedido")
                        .WithOne("PedidoMetodoPago")
                        .HasForeignKey("Proyecto_CPS.Models.PedidoMetodoPago", "PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetodoPago");

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Reserva", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.Cliente", "Clientes")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto_CPS.Models.Mesa", "Mesas")
                        .WithMany("Reservas")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Mesas");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Usuario", b =>
                {
                    b.HasOne("Proyecto_CPS.Models.Cliente", "Cliente")
                        .WithOne("Usuario")
                        .HasForeignKey("Proyecto_CPS.Models.Usuario", "ClienteId");

                    b.HasOne("Proyecto_CPS.Models.Empleado", "Empleado")
                        .WithOne("Usuarios")
                        .HasForeignKey("Proyecto_CPS.Models.Usuario", "EmpleadoId");

                    b.HasOne("Proyecto_CPS.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empleado");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Boleta", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.CategoriaMenu", b =>
                {
                    b.Navigation("Menus");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Cliente", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Reservas");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Empleado", b =>
                {
                    b.Navigation("EmpleadoTurnos");

                    b.Navigation("Usuarios")
                        .IsRequired();
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Menu", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("DetalleMenuPedidos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Mesa", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.MetodoPago", b =>
                {
                    b.Navigation("DetalleMetodoPagos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Pago", b =>
                {
                    b.Navigation("DetallesMetodoPagos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Pedido", b =>
                {
                    b.Navigation("Boletas")
                        .IsRequired();

                    b.Navigation("DetalleMenuPedidos");

                    b.Navigation("Ordenes");

                    b.Navigation("PedidoMetodoPago")
                        .IsRequired();
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Rol", b =>
                {
                    b.Navigation("Empleados");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Turno", b =>
                {
                    b.Navigation("EmpleadoTurnos");
                });

            modelBuilder.Entity("Proyecto_CPS.Models.Usuario", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
